[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language-server.rust-analyzer.config]
inlayHints.parameterHints.enable = false
diagnostics.experimental.enable = true
diagnostics.styleLints.enable = true

[[language]]
name = "bibtex"
auto-format = true
