name: Check crates

on:
  push:
    branches: [main, release**]
  pull_request:
    branches: [main, release**]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  check-all:
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    uses: ./.github/workflows/check-all-reusable.yml
    with:
      crate: ${{ matrix.crate }}

