name: Check All

on:
  workflow_call:
    inputs:
      crate:
        description: Rust crate
        required: true
        type: string

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run format
        run: nix develop -c check-fmt
        working-directory: ./crates

  lint:
    runs-on: ubuntu-24.04
    needs: fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run lint check
        run: nix develop -c check-lint
        working-directory: ./crates

  test:
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run tests
        run: nix develop -c check-test
        working-directory: ./crates

  build:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build .#crates.${{ inputs.crate }}
        working-directory: ./crates
