name: Check crates

on:
  push:
    branches: [main, release**]
  pull_request:
    branches: [main, release**]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    outputs:
      fmt_${{ matrix.crate }}: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run fmt check
        run: nix develop -c check-fmt
        working-directory: ./crates/${{ matrix.crate }}

  lint:
    runs-on: ubuntu-24.04
    needs: fmt
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    # Only run lint if the corresponding crate's fmt job succeeded
    if: ${{ needs.fmt.outputs.fmt_${{ matrix.crate }} == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run lint check
        run: nix develop -c check-lint
        working-directory: ./crates/${{ matrix.crate }}

  test:
    runs-on: ubuntu-24.04
    needs: lint
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run tests
        run: nix develop -c check-test
        working-directory: ./crates/${{ matrix.crate }}

  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build
        run: nix build .#${{ matrix.crate }}
        working-directory: ./crates
