name: Check crates

on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main, release**]
    pull_request:
        branches: [main, release**]
        # Don't run on draft PR's, see: https://github.com/orgs/community/discussions/25722#discussioncomment-3248917
        types: [opened, synchronize, reopened, ready_for_review]
    # Allows us to run the workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  check-crates:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run checks
        run: nix develop -c check-all
        working-directory: ./crates

  build-crates:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        crate: [accumulation, plonk, group, poseidon, schnorr]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build
        run: nix build .#${{ matrix.crate }}
        working-directory: ./crates
